default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.min\.js$
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f12be1ebaa5351c1fc76472de98db2c3446c8253  # frozen: v0.16.10
    hooks:
      - id: ruff-check
        files: panel/
  - repo: https://github.com/pycqa/isort
    rev: 9f905615631c545f5aea2516508109350d1d2f7d  # frozen: 9.0.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/hoxbro/clean_notebook
    rev: ba97036e6f0408aa318165535665c35a9423c352  # frozen: v0.2.1
    hooks:
      - id: clean-notebook
        args: [-i, tags]
        exclude: '^lite/files/.*/'
  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/hoxbro/prettier-pre-commit
    rev: f2fe865d9b280380f8c25ca9e5f4b1c76013df23  # frozen: v3.9.9
    hooks:
      - id: prettier
        entry: prettier --write --ignore-unknown --no-error-on-unmatched-pattern
        types_or: [css]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 10e29bbf6681d33cb90d555ea2f7ea71e162d259  # frozen: v10.12.0
    hooks:
      - id: eslint
        args: ['--config', 'panel/eslint.config.js', 'panel/*.ts', 'panel/models/**/*.ts', '--fix']
        additional_dependencies:
          - 'eslint@9.39.1'
          - '@stylistic/eslint-plugin@5.9.0'
          - '@typescript-eslint/eslint-plugin@8.56.1'
          - '@typescript-eslint/parser@8.56.1'
          - 'typescript-eslint@8.56.1'
ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
