"""
The classic panes, plus the Material UI Typography pane.
"""
from panel_material_ui.pane import MaterialPaneBase, Typography

from ...pane import (
    AVIF, GIF, HTML, ICO, JPG, JSON, PDF, PNG, SVG, VTK, YT, Audio, Bokeh,
    DataFrame, DeckGL, ECharts, HoloViews, Interactive, IPyLeaflet, IPyWidget,
    LaTeX, Markdown, Matplotlib, Pane, PaneBase, ParamFunction, ParamMethod,
    ParamRef, Perspective, Placeholder, Plotly, ReactiveExpr, Reacton, RGGPlot,
    Str, Streamz, Textual, Vega, Video, Vizzu, VTKVolume,
)

__all__ = (
    "Audio",
    "AVIF",
    "Bokeh",
    "DataFrame",
    "DeckGL",
    "ECharts",
    "GIF",
    "HoloViews",
    "HTML",
    "ICO",
    "Interactive",
    "IPyLeaflet",
    "IPyWidget",
    "JPG",
    "JSON",
    "LaTeX",
    "Markdown",
    "MaterialPaneBase",
    "Matplotlib",
    "Pane",
    "PaneBase",
    "ParamFunction",
    "ParamMethod",
    "ParamRef",
    "PDF",
    "Perspective",
    "Placeholder",
    "Plotly",
    "PNG",
    "ReactiveExpr",
    "Reacton",
    "RGGPlot",
    "Str",
    "Streamz",
    "SVG",
    "Textual",
    "Typography",
    "Vega",
    "Video",
    "Vizzu",
    "VTK",
    "VTKVolume",
    "YT",
)
