"""Generate panel.ui reference pages from Panel's classic examples and public API."""

import ast
import inspect
import json
import posixpath
import re

from pathlib import Path
from urllib.parse import urlsplit

SECTIONS = {
    'widgets': 'widgets',
    'layout': 'layouts',
    'pane': 'panes',
    'chat': 'chat',
    'indicators': 'indicators',
    'template': 'templates',
    'wrappers': 'wrappers',
}
GENERATED = '<!-- Generated by ui_reference; do not edit. -->\n'
REFERENCE = re.compile(r'(?<![\w.])pn\.(?:(widgets|layout|pane|chat|indicators|template|wrappers)\.)?([A-Za-z]\w*)')
LINK = re.compile(r'(?<!!)\]\(([^)]+)\)')
CLASSIC_LINK = re.compile(r'\]\((?P<target><[^>]+>|[^\s()]+)(?P<title>\s+"[^"]*")?\)')
FENCE = re.compile(r'^ {0,3}(`{3,}|~{3,})')

# Only these fallbacks execute; other components may require positional arguments.
EXAMPLES = {
    'Button': "pn.ui.Button(label='Click me')",
    'TextInput': "pn.ui.TextInput(label='Name')",
    'DateRangeSlider': 'pn.ui.DateRangeSlider(value=(date.today(), date.today() + timedelta(days=7)))',
    'DatetimeRangeSlider': 'pn.ui.DatetimeRangeSlider(value=(datetime.now(), datetime.now() + timedelta(days=7)))',
}


def _component(module, name, classic):
    return getattr(classic if module is None else getattr(classic, module, None), name, None)


def _references(code, classic, ui):
    """Return safe AST spans, or None if a cell could render a classic component."""
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return None
    spans = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.ImportFrom, ast.Import)):
            aliases = node.names
            if isinstance(node, ast.ImportFrom):
                if node.module and (node.module == 'panel' or node.module.startswith('panel.')):
                    return None
            elif any(alias.name.startswith('panel.') for alias in aliases):
                return None
            elif any(alias.name == 'panel' and alias.asname not in (None, 'pn') for alias in aliases):
                return None
        if isinstance(node, (ast.Assign, ast.AnnAssign, ast.NamedExpr)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            if any(isinstance(target, ast.Name) and target.id == 'pn' for target in targets):
                return None
        if isinstance(node, ast.AugAssign) and isinstance(node.target, ast.Name) and node.target.id == 'pn':
            return None
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in ('getattr', 'setattr'):
            if any(isinstance(arg, ast.Name) and arg.id == 'pn' for arg in node.args):
                return None
        if not isinstance(node, ast.Attribute):
            continue
        if isinstance(node.value, ast.Name) and node.value.id == 'pn':
            module, name = None, node.attr
        elif (isinstance(node.value, ast.Attribute)
              and isinstance(node.value.value, ast.Name)
              and node.value.value.id == 'pn'):
            module, name = node.value.attr, node.attr
        else:
            continue
        obj = _component(module, name, classic)
        if not inspect.isclass(obj) or not hasattr(obj, '_get_model'):
            continue
        if name not in ui.__all__ or obj is not getattr(ui, name):
            return None
        spans.append((node.lineno, node.col_offset, node.end_lineno, node.end_col_offset, name))
    return spans


def _rewrite(code, spans):
    lines = code.encode('utf-8').splitlines(keepends=True)
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line))
    content = code.encode('utf-8')
    for first, start, last, end, name in sorted(spans, reverse=True):
        left, right = offsets[first - 1] + start, offsets[last - 1] + end
        content = content[:left] + f'pn.ui.{name}'.encode() + content[right:]
    return content.decode('utf-8')


def _cells(path):
    return json.loads(path.read_text(encoding='utf-8'))['cells']


def _safe_cells(cells, classic, ui):
    imported = False
    namespace = set(SECTIONS) | set(SECTIONS.values()) | {'ui'}
    for cell in cells:
        source = ''.join(cell['source'])
        if cell['cell_type'] == 'code':
            if re.search(r'(?m)^\s*(?:%|!)|^\s*pn\.extension\(.*\b(?:design|template)\s*=', source):
                return False
            spans = _references(source, classic, ui)
            if spans is None:
                return False
            try:
                tree = ast.parse(source)
            except SyntaxError:
                return False
            imported |= any(
                isinstance(node, ast.Import) and any(
                    alias.name == 'panel' and alias.asname == 'pn' for alias in node.names
                ) for node in ast.walk(tree)
            )
            if any(
                isinstance(node, ast.Name) and node.id == 'pn' and isinstance(node.ctx, (ast.Store, ast.Del))
                for node in ast.walk(tree)
            ):
                return False
            if any(
                isinstance(node, (ast.Assign, ast.AnnAssign, ast.NamedExpr))
                and isinstance(node.value, ast.Attribute)
                and isinstance(node.value.value, ast.Name)
                and node.value.value.id == 'pn' and node.value.attr in namespace
                for node in ast.walk(tree)
            ):
                return False
            if any(isinstance(node, (ast.For, ast.AsyncFor, ast.With, ast.AsyncWith))
                   and any(isinstance(child, ast.Name) and child.id == 'pn'
                           and isinstance(child.ctx, ast.Store) for child in ast.walk(node))
                   for node in ast.walk(tree)):
                return False
            # Do not assume that aliases or reassigned namespace attributes resolve to Panel.
            if any(
                isinstance(node, ast.Attribute) and isinstance(node.ctx, (ast.Store, ast.Del))
                and isinstance(node.value, ast.Name) and node.value.id == 'pn'
                for node in ast.walk(tree)
            ):
                return False
        elif cell['cell_type'] == 'markdown':
            for match in REFERENCE.finditer(source):
                obj = _component(match[1], match[2], classic)
                if inspect.isclass(obj) and (match[2] not in ui.__all__ or obj is not getattr(ui, match[2])):
                    return False
            if re.search(r'(?<![\w.])pn\.(?:widgets|layout|pane|chat|indicators|template|wrappers)\b', source):
                # Unqualified namespace mentions can describe a classic-only API.
                return False
    return imported


def _notebook_page(path, examples, classic, ui):
    cells = _cells(path)
    if not _safe_cells(cells, classic, ui):
        return None
    if not any(
        path.stem in {span[-1] for span in _references(''.join(cell['source']), classic, ui)}
        for cell in cells if cell['cell_type'] == 'code'
    ):
        return None
    chunks = []
    added_import = False
    for cell in cells:
        kind = cell['cell_type']
        if kind == 'code':
            source = ''.join(cell['source'])
            source = _rewrite(source, _references(source, classic, ui))
            if not added_import and 'import panel as pn' in source:
                source = source.replace('import panel as pn', 'import panel as pn\nimport panel.ui', 1)
                added_import = True
            fence = '````' if '```' in source else '```'
            chunks.append(f'{fence}{{pyodide}}\n{source}\n{fence}')
        elif kind == 'markdown':
            source = ''.join(cell['source'])

            def link(match):
                target = match[1]
                path_part, sep, suffix = target.partition('#')
                if (not path_part or path_part.startswith(('/', '<'))
                    or ':' in path_part or '?' in path_part):
                    return match[0]
                if not path_part.endswith('.ipynb'):
                    # Canonical pages have the same section depth as the source notebook.
                    return match[0]
                notebook = (path.parent / path_part).resolve()
                if not notebook.is_relative_to(examples) or not notebook.is_file():
                    return match[0]
                relative = notebook.relative_to(examples)
                section = relative.parts[0]
                if section not in SECTIONS:
                    return match[0]
                component = getattr(getattr(ui, next(key for key, value in SECTIONS.items() if value == section)), notebook.stem, None)
                reusable = (
                    notebook.stem in ui.__all__
                    and component is getattr(ui, notebook.stem)
                    and _safe_cells(_cells(notebook), classic, ui)
                )
                destination = posixpath.join(
                    'reference', section if reusable else 'classic',
                    *(() if reusable else (section,)), *relative.parts[1:-1], notebook.stem,
                )
                current = posixpath.join('reference', path.parent.name)
                return f']({posixpath.relpath(destination, current)}{sep}{suffix})'

            source = LINK.sub(link, source)

            def reference(match):
                obj = _component(match[1], match[2], classic)
                if inspect.isclass(obj) and obj is getattr(ui, match[2], None):
                    return f'pn.ui.{match[2]}'
                return match[0]

            chunks.append(REFERENCE.sub(reference, source))
    return '\n\n'.join(chunks)


def _api_page(name, component):
    description = inspect.getdoc(component) or ''
    description = description.split('\n\n')[0].replace('\n', ' ').strip()
    example = EXAMPLES.get(name)
    if example:
        imports = ''
        if name == 'DateRangeSlider':
            imports = 'from datetime import date, timedelta\n'
        elif name == 'DatetimeRangeSlider':
            imports = 'from datetime import datetime, timedelta\n'
        sample = f'```{{pyodide}}\nimport panel as pn\nimport panel.ui\n{imports}pn.extension()\n\n{example}\n```\n\n'
    else:
        sample = (
            f'Use `pn.ui.{name}` to create this component.\n\n'
        )
    return (
        (f'{description}\n\n' if description else '') + sample + '## API\n\n'
        f'```{{autoclass}} {component.__module__}.{component.__name__}\n   :members:\n```\n'
    )


def _write_generated(path, content):
    if path.exists() and not path.read_text(encoding='utf-8').startswith(GENERATED):
        return
    rendered = GENERATED + content
    if not path.exists() or path.read_text(encoding='utf-8') != rendered:
        path.write_text(rendered, encoding='utf-8')


def relocate_classic_links(app, docname, source):
    """Correct links from nbsite notebooks moved under reference/classic."""
    if not docname.startswith('reference/classic/'):
        return
    if not (Path(app.builder.srcdir) / f'{docname}.md').is_file():
        return

    original = posixpath.dirname(docname.replace('reference/classic/', 'reference/', 1))
    depth = len(original.split('/')) - 1

    def relocate(match):
        target = match['target']
        enclosed = target.startswith('<') and target.endswith('>')
        url = target[1:-1] if enclosed else target
        parsed = urlsplit(url)
        if (not parsed.path or parsed.scheme or parsed.netloc or parsed.path.startswith('/')
            or ':' in parsed.path):
            return match[0]
        remaining = depth
        escaped = False
        for part in parsed.path.split('/'):
            if part == '..':
                remaining -= 1
                escaped |= remaining < 0
            elif part not in ('', '.'):
                remaining += 1
        if not escaped:
            return match[0]
        adjusted = '../' + url
        if enclosed:
            adjusted = f'<{adjusted}>'
        return match[0].replace(target, adjusted, 1)

    fence = None
    lines = []
    for line in source[0].splitlines(keepends=True):
        marker = FENCE.match(line)
        if marker and (fence is None or (
            marker[1][0] == fence[0] and len(marker[1]) >= len(fence)
            and not line[marker.end():].strip()
        )):
            fence = marker[1] if fence is None else None
            lines.append(line)
        else:
            lines.append(line if fence else CLASSIC_LINK.sub(relocate, line))
    source[0] = ''.join(lines)


def generate_ui_reference(app):
    """Run after nbsite generates classic pages, before Sphinx scans sources."""
    import panel as pn
    import panel.ui as ui

    from panel.viewable import Viewable

    gallery_conf = app.config.nbsite_gallery_conf
    source = gallery_conf['galleries']['reference/classic']['source']
    examples = (Path(app.builder.srcdir) / gallery_conf['examples_dir'] / source).resolve()
    output = Path(app.builder.srcdir) / 'reference'
    index = [
        '# Component Gallery', '',
        ':::{important}',
        'Looking for the original Panel components? Browse the '
        '[classic component gallery](classic/index). The components below use `panel.ui`.',
        ':::', '',
    ]
    section_indexes = []
    for module_name, section in SECTIONS.items():
        module = getattr(ui, module_name)
        names = sorted(name for name in ui.__all__ if (
            getattr(module, name, None) is getattr(ui, name)
            and inspect.isclass(component := getattr(ui, name))
            and issubclass(component, Viewable)
        ))
        if not names:
            continue
        section_indexes.append(f'{section}/index')
        section_dir = output / section
        section_dir.mkdir(parents=True, exist_ok=True)
        if section != 'templates':
            index.extend([f'## {section.title()}', '', ', '.join(
                f'[{name}]({section}/{name})' for name in names
            ), ''])
        _write_generated(section_dir / 'index.md',
            f'# {section.title()}\n\n'
            + '\n'.join(f'- [{name}]({name})' for name in names)
            + '\n\n```{toctree}\n:hidden:\n\n'
            + '\n'.join(names) + '\n```\n',
        )
        for name in names:
            component = getattr(ui, name)
            notebook = examples / section / f'{name}.ipynb'
            content = _notebook_page(notebook, examples, pn, ui) if notebook.is_file() else None
            if content is None:
                content = _api_page(name, component)
                if notebook.is_file() and any(
                    getattr(getattr(pn, module_name, None), name, None) is component
                    for module_name in SECTIONS
                ):
                    content = (
                        f'This component is also available in the '
                        f'[classic reference](../classic/{section}/{name}).\n\n{content}'
                    )
            _write_generated(section_dir / f'{name}.md', f'# {name}\n\n{content}\n')
    classic_templates = sorted((examples / 'templates').glob('*.ipynb'))
    index.extend([
        '## Templates', '',
        'Classic templates are still available, but new applications should use '
        '[`pn.ui.Page`](templates/Page). Browse the '
        '[classic template reference](classic/templates/index) for the older APIs.', '',
        ', '.join(f'[{path.stem}](classic/templates/{path.stem})' for path in classic_templates), '',
    ])
    index.extend(['```{toctree}', ':hidden:', '', 'classic/index', *section_indexes, '```', ''])
    _write_generated(output / 'index.md', '\n'.join(index) + '\n')


def setup(app):
    app.connect('builder-inited', generate_ui_reference, priority=600)
    app.connect('source-read', relocate_classic_links)
    return {'parallel_read_safe': True, 'parallel_write_safe': True}
