"""Generate panel.ui reference pages from PMUI and identity-compatible classic notebooks."""

import ast
import inspect
import io
import json
import os
import posixpath
import re
import tarfile
import tempfile

from importlib.metadata import version
from importlib.util import find_spec
from pathlib import Path
from urllib.parse import urlsplit
from urllib.request import urlopen

SECTIONS = {
    'widgets': 'widgets',
    'layout': 'layouts',
    'pane': 'panes',
    'chat': 'chat',
    'indicators': 'indicators',
    'template': 'templates',
    'wrappers': 'wrappers',
}
GENERATED = '<!-- Generated by ui_reference; do not edit. -->\n'
REFERENCE = re.compile(r'(?<![\w.])pn\.(?:(widgets|layout|pane|chat|indicators|template|wrappers)\.)?([A-Za-z]\w*)')
LINK = re.compile(r'(?<!!)\]\(([^)]+)\)')
CLASSIC_LINK = re.compile(r'\]\((?P<target><[^>]+>|[^\s()]+)(?P<title>\s+"[^"]*")?\)')
FENCE = re.compile(r'^ {0,3}(`{3,}|~{3,})')

# Only these fallbacks execute; other components may require positional arguments.
EXAMPLES = {
    'Button': "pn.ui.Button(label='Click me')",
    'TextInput': "pn.ui.TextInput(label='Name')",
    'DateRangeSlider': 'pn.ui.DateRangeSlider(value=(date.today(), date.today() + timedelta(days=7)))',
    'DatetimeRangeSlider': 'pn.ui.DatetimeRangeSlider(value=(datetime.now(), datetime.now() + timedelta(days=7)))',
}


def _component(module, name, classic):
    return getattr(classic if module is None else getattr(classic, module, None), name, None)


def _references(code, classic, ui):
    """Return safe AST spans, or None if a cell could render a classic component."""
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return None
    spans = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.ImportFrom, ast.Import)):
            aliases = node.names
            if isinstance(node, ast.ImportFrom):
                if node.module and (node.module == 'panel' or node.module.startswith('panel.')):
                    return None
            elif any(alias.name.startswith('panel.') for alias in aliases):
                return None
            elif any(alias.name == 'panel' and alias.asname not in (None, 'pn') for alias in aliases):
                return None
        if isinstance(node, (ast.Assign, ast.AnnAssign, ast.NamedExpr)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            if any(isinstance(target, ast.Name) and target.id == 'pn' for target in targets):
                return None
        if isinstance(node, ast.AugAssign) and isinstance(node.target, ast.Name) and node.target.id == 'pn':
            return None
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in ('getattr', 'setattr'):
            if any(isinstance(arg, ast.Name) and arg.id == 'pn' for arg in node.args):
                return None
        if not isinstance(node, ast.Attribute):
            continue
        if isinstance(node.value, ast.Name) and node.value.id == 'pn':
            module, name = None, node.attr
        elif (isinstance(node.value, ast.Attribute)
              and isinstance(node.value.value, ast.Name)
              and node.value.value.id == 'pn'):
            module, name = node.value.attr, node.attr
        else:
            continue
        obj = _component(module, name, classic)
        if not inspect.isclass(obj) or not hasattr(obj, '_get_model'):
            continue
        if name not in ui.__all__ or obj is not getattr(ui, name):
            return None
        spans.append((node.lineno, node.col_offset, node.end_lineno, node.end_col_offset, f'pn.ui.{name}'))
    return spans


def _rewrite(code, spans):
    lines = code.encode('utf-8').splitlines(keepends=True)
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line))
    content = code.encode('utf-8')
    for first, start, last, end, name in sorted(spans, reverse=True):
        left, right = offsets[first - 1] + start, offsets[last - 1] + end
        content = content[:left] + name.encode() + content[right:]
    return content.decode('utf-8')


def _cells(path):
    return json.loads(path.read_text(encoding='utf-8'))['cells']


def _material_codes(cells, ui):
    """Rewrite PMUI imports and references only for components exported by panel.ui."""
    imported = set()
    material_imported = False
    for cell in cells:
        if cell['cell_type'] != 'code':
            continue
        tree = ast.parse(''.join(cell['source']))
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module == 'panel_material_ui':
                for alias in node.names:
                    if alias.asname or alias.name not in set(ui.__all__) | {'COLORS'}:
                        raise ValueError(f'Unsupported PMUI import: {alias.name}')
                    if alias.name != 'COLORS':
                        imported.add(alias.name)
            elif isinstance(node, ast.Import) and any(alias.name == 'panel_material_ui' and alias.asname == 'pmui'
                                                        for alias in node.names):
                material_imported = True
    codes = []
    used = set()
    has_import = False
    for cell in cells:
        if cell['cell_type'] != 'code':
            continue
        source = ''.join(cell['source'])
        if re.search(r'(?m)^\s*(?:%|!)', source):
            raise ValueError('Notebook contains magic or shell commands')
        tree = ast.parse(source)
        spans = []
        attribute_bases = {id(node.value) for node in ast.walk(tree) if isinstance(node, ast.Attribute)}
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                if any(alias.name == 'panel_material_ui' and alias.asname != 'pmui'
                       or alias.name.startswith('panel_material_ui.') for alias in node.names):
                    raise ValueError('Unsupported PMUI module import')
                if any(alias.name == 'panel' and alias.asname == 'pn' for alias in node.names):
                    has_import = True
                if any(alias.name == 'panel_material_ui' for alias in node.names):
                    if len(node.names) != 1:
                        raise ValueError('Combined PMUI imports are unsupported')
                    spans.append((node.lineno, node.col_offset, node.end_lineno, node.end_col_offset, 'import panel.ui'))
                    has_import = True
            elif isinstance(node, ast.ImportFrom) and node.module == 'panel_material_ui':
                imports = [alias.name for alias in node.names]
                replacement = 'import panel.ui'
                if 'COLORS' in imports:
                    replacement += '\nCOLORS = ["default", "primary", "secondary", "error", "info", "success", "warning", "light", "dark", "danger"]'
                spans.append((node.lineno, node.col_offset, node.end_lineno, node.end_col_offset, replacement))
                has_import = True
            elif isinstance(node, ast.ImportFrom) and node.module and node.module.startswith('panel_material_ui.'):
                raise ValueError('Unsupported PMUI submodule import')
            elif isinstance(node, ast.Name) and node.id in imported and isinstance(node.ctx, ast.Load):
                spans.append((node.lineno, node.col_offset, node.end_lineno, node.end_col_offset, f'pn.ui.{node.id}'))
                used.add(node.id)
            elif isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name) and node.value.id == 'pmui':
                if node.attr == 'widgets':
                    continue
                if node.attr not in ui.__all__:
                    raise ValueError(f'PMUI component is not exported by panel.ui: {node.attr}')
                spans.append((node.lineno, node.col_offset, node.end_lineno, node.end_col_offset, f'pn.ui.{node.attr}'))
                used.add(node.attr)
            elif (isinstance(node, ast.Attribute) and isinstance(node.value, ast.Attribute)
                  and isinstance(node.value.value, ast.Name) and node.value.value.id == 'pmui'
                  and node.value.attr == 'widgets'):
                if node.attr not in ui.__all__:
                    raise ValueError(f'Unsupported PMUI namespace: {node.value.attr}.{node.attr}')
                spans.append((node.lineno, node.col_offset, node.end_lineno, node.end_col_offset, f'pn.ui.{node.attr}'))
                used.add(node.attr)
            elif isinstance(node, ast.Name) and node.id in imported | {'pmui'} and isinstance(node.ctx, (ast.Store, ast.Del)):
                raise ValueError(f'PMUI alias is reassigned: {node.id}')
            elif (isinstance(node, ast.Name) and node.id == 'pmui' and isinstance(node.ctx, ast.Load)
                  and id(node) not in attribute_bases):
                raise ValueError('Unsupported direct use of pmui module')
        codes.append(_rewrite(source, spans))
    if not has_import:
        raise ValueError('Notebook does not import Panel or PMUI')
    if any('pmui' in {node.id for node in ast.walk(ast.parse(''.join(cell['source'])))
                      if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load)}
           for cell in cells if cell['cell_type'] == 'code') and not material_imported:
        raise ValueError('Notebook uses pmui without importing it')
    return codes, used


def _safe_cells(cells, classic, ui):
    imported = False
    namespace = set(SECTIONS) | set(SECTIONS.values()) | {'ui'}
    for cell in cells:
        source = ''.join(cell['source'])
        if cell['cell_type'] == 'code':
            if re.search(r'(?m)^\s*(?:%|!)|^\s*pn\.extension\(.*\b(?:design|template)\s*=', source):
                return False
            spans = _references(source, classic, ui)
            if spans is None:
                return False
            try:
                tree = ast.parse(source)
            except SyntaxError:
                return False
            imported |= any(
                isinstance(node, ast.Import) and any(
                    alias.name == 'panel' and alias.asname == 'pn' for alias in node.names
                ) for node in ast.walk(tree)
            )
            if any(
                isinstance(node, ast.Name) and node.id == 'pn' and isinstance(node.ctx, (ast.Store, ast.Del))
                for node in ast.walk(tree)
            ):
                return False
            if any(
                isinstance(node, (ast.Assign, ast.AnnAssign, ast.NamedExpr))
                and isinstance(node.value, ast.Attribute)
                and isinstance(node.value.value, ast.Name)
                and node.value.value.id == 'pn' and node.value.attr in namespace
                for node in ast.walk(tree)
            ):
                return False
            if any(isinstance(node, (ast.For, ast.AsyncFor, ast.With, ast.AsyncWith))
                   and any(isinstance(child, ast.Name) and child.id == 'pn'
                           and isinstance(child.ctx, ast.Store) for child in ast.walk(node))
                   for node in ast.walk(tree)):
                return False
            # Do not assume that aliases or reassigned namespace attributes resolve to Panel.
            if any(
                isinstance(node, ast.Attribute) and isinstance(node.ctx, (ast.Store, ast.Del))
                and isinstance(node.value, ast.Name) and node.value.id == 'pn'
                for node in ast.walk(tree)
            ):
                return False
        elif cell['cell_type'] == 'markdown':
            for match in REFERENCE.finditer(source):
                obj = _component(match[1], match[2], classic)
                if inspect.isclass(obj) and (match[2] not in ui.__all__ or obj is not getattr(ui, match[2])):
                    return False
            if re.search(r'(?<![\w.])pn\.(?:widgets|layout|pane|chat|indicators|template|wrappers)\b', source):
                # Unqualified namespace mentions can describe a classic-only API.
                return False
    return imported


def _notebook_page(path, examples, classic, ui):
    cells = _cells(path)
    if not _safe_cells(cells, classic, ui):
        return None
    if not any(
        f'pn.ui.{path.stem}' in {span[-1] for span in _references(''.join(cell['source']), classic, ui)}
        for cell in cells if cell['cell_type'] == 'code'
    ):
        return None
    chunks = []
    added_import = False
    for cell in cells:
        kind = cell['cell_type']
        if kind == 'code':
            source = ''.join(cell['source'])
            source = _rewrite(source, _references(source, classic, ui))
            if not added_import and 'import panel as pn' in source:
                source = source.replace('import panel as pn', 'import panel as pn\nimport panel.ui', 1)
                added_import = True
            fence = '````' if '```' in source else '```'
            chunks.append(f'{fence}{{pyodide}}\n{source}\n{fence}')
        elif kind == 'markdown':
            source = ''.join(cell['source'])

            def link(match):
                target = match[1]
                path_part, sep, suffix = target.partition('#')
                if (not path_part or path_part.startswith(('/', '<'))
                    or ':' in path_part or '?' in path_part):
                    return match[0]
                if not path_part.endswith('.ipynb'):
                    # Canonical pages have the same section depth as the source notebook.
                    return match[0]
                notebook = (path.parent / path_part).resolve()
                if not notebook.is_relative_to(examples) or not notebook.is_file():
                    return match[0]
                relative = notebook.relative_to(examples)
                section = relative.parts[0]
                if section not in SECTIONS:
                    return match[0]
                component = getattr(getattr(ui, next(key for key, value in SECTIONS.items() if value == section)), notebook.stem, None)
                reusable = (
                    notebook.stem in ui.__all__
                    and component is getattr(ui, notebook.stem)
                    and _safe_cells(_cells(notebook), classic, ui)
                )
                destination = posixpath.join(
                    'reference', section if reusable else 'classic',
                    *(() if reusable else (section,)), *relative.parts[1:-1], notebook.stem,
                )
                current = posixpath.join('reference', path.parent.name)
                return f']({posixpath.relpath(destination, current)}{sep}{suffix})'

            source = LINK.sub(link, source)

            def reference(match):
                obj = _component(match[1], match[2], classic)
                if inspect.isclass(obj) and obj is getattr(ui, match[2], None):
                    return f'pn.ui.{match[2]}'
                return match[0]

            chunks.append(REFERENCE.sub(reference, source))
    return '\n\n'.join(chunks)


def _material_page(path, examples, ui, name=None):
    cells = _cells(path)
    codes, used = _material_codes(cells, ui)
    if (name or path.stem) not in used and path.stem not in used:
        raise ValueError(f'{path} does not demonstrate pn.ui.{name or path.stem}')
    chunks = []
    code_iter = iter(codes)
    for cell in cells:
        if cell['cell_type'] == 'code':
            source = next(code_iter)
            if 'import panel as pn' in source and 'import panel.ui' not in source:
                source = source.replace('import panel as pn', 'import panel as pn\nimport panel.ui', 1)
            fence = '````' if '```' in source else '```'
            chunks.append(f'{fence}{{pyodide}}\n{source}\n{fence}')
        elif cell['cell_type'] == 'markdown':
            source = ''.join(cell['source'])

            def link(match):
                target = match[1]
                path_part, sep, suffix = target.partition('#')
                if (not path_part.endswith('.ipynb') or path_part.startswith(('/', '<'))
                    or ':' in path_part or '?' in path_part):
                    return match[0]
                notebook = (path.parent / path_part).resolve()
                if not notebook.is_relative_to(examples) or not notebook.is_file():
                    return match[0]
                relative = notebook.relative_to(examples)
                section = relative.parts[0]
                destination = {'page': 'templates', 'menus': 'widgets'}.get(section, section)
                if destination not in SECTIONS.values():
                    return match[0]
                target_name = notebook.stem
                if target_name not in ui.__all__:
                    target_name = next((name for name in ui.__all__
                                        if getattr(ui, name).__name__ == notebook.stem), target_name)
                if target_name not in ui.__all__:
                    return match[0]
                current = posixpath.join('reference', {'page': 'templates', 'menus': 'widgets'}.get(path.parent.name, path.parent.name))
                return f']({posixpath.relpath(posixpath.join("reference", destination, target_name), current)}{sep}{suffix})'

            source = LINK.sub(link, source)
            source = re.sub(
                r'(?<![\w.])pmui\.(?:widgets\.)?([A-Za-z]\w*)',
                lambda match: f'pn.ui.{match[1]}' if match[1] in ui.__all__ else match[0],
                source,
            )
            chunks.append(source)
    return '\n\n'.join(chunks)


def _material_examples(app):
    configured = getattr(app.config, 'ui_reference_pmui_source', None) or os.environ.get('PANEL_UI_REFERENCE_PMUI_SOURCE')
    if configured:
        root = Path(configured).expanduser().resolve()
        if (root / 'examples/reference').is_dir():
            root /= 'examples/reference'
        if not root.is_dir():
            raise FileNotFoundError(f'PMUI notebook source not found: {root}')
        return root
    spec = find_spec('panel_material_ui')
    if spec and spec.origin:
        package = Path(spec.origin).resolve().parent
        for root in (package / 'examples/reference', package.parent.parent / 'examples/reference'):
            if (root / 'widgets/Button.ipynb').is_file():
                return root
        release = version('panel-material-ui')
        url = f'https://github.com/panel-extensions/panel-material-ui/archive/refs/tags/v{release}.tar.gz'
        try:
            with urlopen(url, timeout=30) as response:
                archive = io.BytesIO(response.read())
        except OSError as exc:
            raise FileNotFoundError(
                f'PMUI reference notebooks are not installed and the source archive at {url} '
                'could not be downloaded. Set PANEL_UI_REFERENCE_PMUI_SOURCE to a local checkout.'
            ) from exc
        app._pmui_reference_dir = tempfile.TemporaryDirectory(prefix='panel-pmui-reference-')
        root = Path(app._pmui_reference_dir.name)
        with tarfile.open(fileobj=archive, mode='r:gz') as source:
            for member in source:
                parts = Path(member.name).parts
                if not member.isfile() or len(parts) < 5 or parts[1:3] != ('examples', 'reference'):
                    continue
                if not member.name.endswith('.ipynb'):
                    continue
                destination = root.joinpath(*parts[3:])
                if not destination.resolve().is_relative_to(root.resolve()):
                    continue
                destination.parent.mkdir(parents=True, exist_ok=True)
                with source.extractfile(member) as notebook, destination.open('wb') as output:
                    output.write(notebook.read())
        if (root / 'widgets/Button.ipynb').is_file():
            return root
        raise FileNotFoundError(f'PMUI source archive at {url} has no reference notebooks')
    return None


def _api_page(name, component):
    description = inspect.getdoc(component) or ''
    description = description.split('\n\n')[0].replace('\n', ' ').strip()
    example = EXAMPLES.get(name)
    if example:
        imports = ''
        if name == 'DateRangeSlider':
            imports = 'from datetime import date, timedelta\n'
        elif name == 'DatetimeRangeSlider':
            imports = 'from datetime import datetime, timedelta\n'
        sample = f'```{{pyodide}}\nimport panel as pn\nimport panel.ui\n{imports}pn.extension()\n\n{example}\n```\n\n'
    else:
        sample = (
            f'Use `pn.ui.{name}` to create this component.\n\n'
        )
    return (
        (f'{description}\n\n' if description else '') + sample + '## API\n\n'
        f'```{{autoclass}} {component.__module__}.{component.__name__}\n   :members:\n```\n'
    )


def _write_generated(path, content):
    if path.exists() and not path.read_text(encoding='utf-8').startswith(GENERATED):
        return
    rendered = GENERATED + content
    if not path.exists() or path.read_text(encoding='utf-8') != rendered:
        path.write_text(rendered, encoding='utf-8')


def prepare_ui_gallery(app):
    """Let nbsite discover UI pages from a temporary view of the original notebooks."""
    from nbsite.gallery.gen import DEFAULT_GALLERY_CONF

    import panel.ui as ui

    from panel.viewable import Viewable

    material = _material_examples(app)
    if material is None:
        raise FileNotFoundError('PMUI reference notebooks are unavailable.')
    app._ui_reference_material = material
    conf = app.config.nbsite_gallery_conf
    source = conf['galleries']['reference/classic']['source']
    examples = (Path(app.builder.srcdir) / conf.get('examples_dir', DEFAULT_GALLERY_CONF['examples_dir']) / source).resolve()
    app._ui_reference_gallery = tempfile.TemporaryDirectory(prefix='panel-ui-gallery-')
    root = Path(app._ui_reference_gallery.name)
    for module_name, section in SECTIONS.items():
        module = getattr(ui, module_name)
        names = sorted(name for name in ui.__all__ if (
            getattr(module, name, None) is getattr(ui, name)
            and inspect.isclass(component := getattr(ui, name))
            and issubclass(component, Viewable)
        ))
        directory = root / section
        directory.mkdir()
        for name in names:
            component = getattr(ui, name)
            material_section = {'templates': 'page'}.get(section, section)
            notebook = material / material_section / f'{name}.ipynb'
            if not notebook.is_file():
                notebook = material / material_section / f'{component.__name__}.ipynb'
            if not notebook.is_file():
                notebook = next((candidate for other in ('widgets', 'indicators', 'menus')
                                 if (candidate := material / other / f'{component.__name__}.ipynb').is_file()), notebook)
            if not notebook.is_file():
                notebook = examples / section / f'{name}.ipynb'
            if notebook.is_file():
                (directory / f'{name}.ipynb').symlink_to(notebook)
            else:
                (directory / f'{name}.py').touch()
    gallery = app.config.nbsite_gallery_conf['galleries']['reference']
    gallery['source'] = str(root)
    gallery['sections'] = [
        *[section for section in SECTIONS.values() if section != 'templates'],
        {'path': 'templates', 'title': 'Templates',
         'description': ('Classic templates are still available, but new applications should use '
                         '`pn.ui.Page <templates/Page.html>`_. Browse the '
                         '`classic template reference <classic/templates/index.html>`_ for the older APIs.')},
        {'path': 'classic', 'title': 'Classic Reference',
         'description': 'The original Panel components and their reference guides.',
         'items': [{'title': 'Classic Component Gallery', 'url': 'classic/index.html',
                    'thumbnail': 'https://assets.holoviz.org/panel/thumbnails/reference/widgets/Button.png'}]},
    ]
    gallery['extensions'] = ['*.ipynb', '*.py']
    gallery['as_pyodide'] = False
    gallery['skip_rst_notebook_directive'] = True
    gallery['thumbnail_url'] = conf.get('thumbnail_url', DEFAULT_GALLERY_CONF['thumbnail_url'])
    gallery['thumbnail_source'] = 'reference/ui'
    gallery['normalize_titles'] = False
    gallery['no_image_thumb'] = True
    gallery['intro'] = ('The components below use ``panel.ui``.\n\n'
                        '.. toctree::\n   :hidden:\n\n   classic/index\n')


def relocate_classic_links(app, docname, source):
    """Correct links from nbsite notebooks moved under reference/classic."""
    if not docname.startswith('reference/classic/'):
        return
    if not (Path(app.builder.srcdir) / f'{docname}.md').is_file():
        return

    original = posixpath.dirname(docname.replace('reference/classic/', 'reference/', 1))
    depth = len(original.split('/')) - 1

    def relocate(match):
        target = match['target']
        enclosed = target.startswith('<') and target.endswith('>')
        url = target[1:-1] if enclosed else target
        parsed = urlsplit(url)
        if (not parsed.path or parsed.scheme or parsed.netloc or parsed.path.startswith('/')
            or ':' in parsed.path):
            return match[0]
        remaining = depth
        escaped = False
        for part in parsed.path.split('/'):
            if part == '..':
                remaining -= 1
                escaped |= remaining < 0
            elif part not in ('', '.'):
                remaining += 1
        if not escaped:
            return match[0]
        adjusted = '../' + url
        if enclosed:
            adjusted = f'<{adjusted}>'
        return match[0].replace(target, adjusted, 1)

    fence = None
    lines = []
    for line in source[0].splitlines(keepends=True):
        marker = FENCE.match(line)
        if marker and (fence is None or (
            marker[1][0] == fence[0] and len(marker[1]) >= len(fence)
            and not line[marker.end():].strip()
        )):
            fence = marker[1] if fence is None else None
            lines.append(line)
        else:
            lines.append(line if fence else CLASSIC_LINK.sub(relocate, line))
    source[0] = ''.join(lines)


def resolve_gallery_index_links(app, docname, source):
    if docname.startswith('reference/'):
        return
    source[0] = re.sub(r'((?:\.\./)+reference/index)\.md(?=#|\))', r'\1.rst', source[0])


def generate_ui_reference(app):
    """Run after nbsite generates classic pages, before Sphinx scans sources."""
    import panel as pn
    import panel.ui as ui

    from panel.viewable import Viewable

    gallery_conf = app.config.nbsite_gallery_conf
    source = gallery_conf['galleries']['reference/classic']['source']
    examples = (Path(app.builder.srcdir) / gallery_conf['examples_dir'] / source).resolve()
    material = getattr(app, '_ui_reference_material', None) or _material_examples(app)
    if material is None:
        raise FileNotFoundError(
            'PMUI reference notebooks are unavailable. Set PANEL_UI_REFERENCE_PMUI_SOURCE '
            'to a panel-material-ui checkout (or examples/reference directory), or provide '
            'notebooks in the installed panel_material_ui package.'
        )
    output = Path(app.builder.srcdir) / 'reference'
    for module_name, section in SECTIONS.items():
        module = getattr(ui, module_name)
        names = sorted(name for name in ui.__all__ if (
            getattr(module, name, None) is getattr(ui, name)
            and inspect.isclass(component := getattr(ui, name))
            and issubclass(component, Viewable)
        ))
        if not names:
            continue
        section_dir = output / section
        section_dir.mkdir(parents=True, exist_ok=True)
        old_section_index = section_dir / 'index.md'
        if old_section_index.is_file() and old_section_index.read_text(encoding='utf-8').startswith(GENERATED):
            old_section_index.unlink()
        for name in names:
            component = getattr(ui, name)
            notebook = examples / section / f'{name}.ipynb'
            material_section = {'templates': 'page'}.get(section, section)
            material_notebook = material / material_section / f'{name}.ipynb'
            if not material_notebook.is_file() and component.__name__ != name:
                material_notebook = material / material_section / f'{component.__name__}.ipynb'
            if not material_notebook.is_file():
                for other_section in ('widgets', 'indicators', 'menus'):
                    candidate = material / other_section / f'{component.__name__}.ipynb'
                    if candidate.is_file():
                        material_notebook = candidate
                        break
            if material_notebook.is_file():
                try:
                    content = _material_page(material_notebook, material, ui, name)
                except (ValueError, SyntaxError) as exc:
                    raise ValueError(f'Cannot convert PMUI notebook {material_notebook}: {exc}') from exc
            else:
                content = _notebook_page(notebook, examples, pn, ui) if notebook.is_file() else None
            if content is None:
                content = _api_page(name, component)
                if notebook.is_file() and any(
                    getattr(getattr(pn, module_name, None), name, None) is component
                    for module_name in SECTIONS
                ):
                    content = (
                        f'This component is also available in the '
                        f'[classic reference](../classic/{section}/{name}).\n\n{content}'
                    )
            _write_generated(section_dir / f'{name}.md', f'# {name}\n\n{content}\n')
    old_index = output / 'index.md'
    if old_index.is_file() and old_index.read_text(encoding='utf-8').startswith(GENERATED):
        old_index.unlink()


def cleanup_ui_gallery(app, exception):
    if temporary := getattr(app, '_ui_reference_gallery', None):
        temporary.cleanup()
    if temporary := getattr(app, '_pmui_reference_dir', None):
        temporary.cleanup()


def setup(app):
    app.connect('builder-inited', prepare_ui_gallery, priority=400)
    app.connect('builder-inited', generate_ui_reference, priority=600)
    app.connect('source-read', relocate_classic_links)
    app.connect('source-read', resolve_gallery_index_links)
    app.connect('build-finished', cleanup_ui_gallery)
    return {'parallel_read_safe': True, 'parallel_write_safe': True}
