from __future__ import annotations

import pathlib

from panel.widgets.button import BUTTON_TYPES

_ROOT = pathlib.Path(__file__).parent
_CSS = _ROOT / "css"

_COMPONENTS_CSS = _CSS / "components"

from .base import (
    DefaultTheme, Design, Inherit,
)

#from ..widgets
from ..layout import ListPanel, Accordion
from ..widgets import CheckBoxGroup, DatePicker, Checkbox, IntSlider
from ..pane import Markdown
from ..widgets.button import _ClickButton


class Material3DefaultTheme(DefaultTheme):
    # define a global, base CSS here
    #base_css = param.Filename(default=_CSS / 'quansight_default.css')
    pass
    

class Material3Design(Design):

    _resources = {
        'font': {
            'Roboto': "https://fonts.googleapis.com/css?family=Roboto:300,400,500",
            'Material Symbols Outlined': "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200",
        },
        # 'css_files':["http://localhost:8080/material3_css/autogenerated.css"]
    }

    modifiers = {
        # Covers Column, Row, Card, ChatFeed, WidgetBox
        ListPanel: {
            'css_classes': ['surface']
        },
        
        Accordion: {
            'css_classes': ['surface']
        },
        
        # TO DO
        

        # TO FINISH - Fix the various states of the components (hover, disabled, error ...)
        
        CheckBoxGroup: {
            'stylesheets': [Inherit,
                            (_COMPONENTS_CSS / "pn_widgets_checkbox.css").read_text(encoding='utf-8'), 
                            ]
        },
        

        DatePicker: {
            'stylesheets': [Inherit,
                            (_COMPONENTS_CSS / "pn_widgets_datepicker.css").read_text(encoding='utf-8'), 
                            ]
        },


        Markdown:{
              'stylesheets': [Inherit,
                            (_COMPONENTS_CSS / "pn_widgets_markdown.css").read_text(encoding='utf-8'), 
                            ]
        },

        Checkbox: {
            'stylesheets': [Inherit,
                            {CDN_DIST}bundled/theme/pn_widgets_checkbox.css").read_text(encoding='utf-8'), 
                            ]
        },


        # Check the hover and other states
        _ClickButton: {
            'stylesheets': [Inherit,
                            (_COMPONENTS_CSS / "pn_widgets_clickbutton.css").read_text(encoding='utf-8'), 
                            ]
        },


        # DONE
        IntSlider: {
            'css_classes': [ ],
            # 'bar_color': 'red',
            'stylesheets': [Inherit,
                            (_COMPONENTS_CSS / "pn_widgets_intslider.css").read_text(encoding='utf-8'), 
                            ]
        }
    }

    _themes = {
        'default': Material3DefaultTheme, 
        # 'default': Material3LightTheme, 
        # 'dark': Material3DarkTheme, 
    }

