"""
Material UI widgets, plus the classic widgets that have no Material equivalent.
"""
from panel_material_ui.widgets import (
    ArrayInput, AutocompleteInput, Avatar, Breadcrumbs, Button, ButtonIcon,
    Checkbox, CheckBoxGroup, CheckButtonGroup, Chip, CircularProgress,
    ColorMap, ColorPicker, CrossSelector, DatePicker, DateRangePicker,
    DateRangeSlider, DateSlider, DatetimeInput, DatetimePicker,
    DatetimeRangeInput, DatetimeRangePicker, DatetimeRangeSlider,
    DatetimeSlider, DictInput, DiscretePlayer, DiscreteSlider,
    EditableFloatSlider, EditableIntRangeSlider, EditableIntSlider,
    EditableRangeSlider, Fab, FileDownload, FileInput, FileSelector,
    FloatInput, FloatSlider, IconButton, IntInput, IntRangeSlider, IntSlider,
    LinearProgress, ListInput, LiteralInput, LoadingSpinner, MenuBar,
    MenuButton, MenuList, MenuToggle, MultiChoice, MultiPill, MultiSelect,
    NestedBreadcrumbs, NestedSelect, NumberInput, Pagination, PasswordInput,
    Pill, Player, Progress, RadioBoxGroup, RadioButtonGroup, RangeSlider,
    Rating, Select, SpeedDial, SplitButton, StepperMenu, Switch, TabMenu,
    TextAreaInput, TextInput, TimePicker, Toggle, ToggleIcon, Tree, TupleInput,
)

from ...widgets import (
    BooleanStatus, CodeEditor, CompositeWidget, Debugger, Dial, FileDropper,
    Gauge, Grammar, GrammarList, JSONEditor, LinearGauge, Number, SpeechToText,
    StaticText, Tabulator, Terminal, TextEditor, TextToSpeech, ToggleGroup,
    TooltipIcon, Trend, Utterance, VideoStream, Voice, Widget, WidgetBase,
)
from ..indicators import Tqdm

__all__ = (
    "ArrayInput",
    "AutocompleteInput",
    "Avatar",
    "BooleanStatus",
    "Breadcrumbs",
    "Button",
    "ButtonIcon",
    "Checkbox",
    "CheckBoxGroup",
    "CheckButtonGroup",
    "Chip",
    "CircularProgress",
    "CodeEditor",
    "ColorMap",
    "ColorPicker",
    "CompositeWidget",
    "CrossSelector",
    "DatePicker",
    "DateRangePicker",
    "DateRangeSlider",
    "DateSlider",
    "DatetimeInput",
    "DatetimePicker",
    "DatetimeRangeInput",
    "DatetimeRangePicker",
    "DatetimeRangeSlider",
    "DatetimeSlider",
    "Debugger",
    "Dial",
    "DictInput",
    "DiscretePlayer",
    "DiscreteSlider",
    "EditableFloatSlider",
    "EditableIntRangeSlider",
    "EditableIntSlider",
    "EditableRangeSlider",
    "Fab",
    "FileDownload",
    "FileDropper",
    "FileInput",
    "FileSelector",
    "FloatInput",
    "FloatSlider",
    "Gauge",
    "Grammar",
    "GrammarList",
    "IconButton",
    "IntInput",
    "IntRangeSlider",
    "IntSlider",
    "JSONEditor",
    "LinearGauge",
    "LinearProgress",
    "ListInput",
    "LiteralInput",
    "LoadingSpinner",
    "MenuBar",
    "MenuButton",
    "MenuList",
    "MenuToggle",
    "MultiChoice",
    "MultiPill",
    "MultiSelect",
    "NestedBreadcrumbs",
    "NestedSelect",
    "Number",
    "NumberInput",
    "Pagination",
    "PasswordInput",
    "Pill",
    "Player",
    "Progress",
    "RadioBoxGroup",
    "RadioButtonGroup",
    "RangeSlider",
    "Rating",
    "Select",
    "SpeechToText",
    "SpeedDial",
    "SplitButton",
    "StaticText",
    "StepperMenu",
    "Switch",
    "TabMenu",
    "Tabulator",
    "Terminal",
    "TextAreaInput",
    "TextEditor",
    "TextInput",
    "TextToSpeech",
    "TimePicker",
    "Toggle",
    "ToggleGroup",
    "ToggleIcon",
    "TooltipIcon",
    "Tqdm",
    "Tree",
    "Trend",
    "TupleInput",
    "Utterance",
    "VideoStream",
    "Voice",
    "Widget",
    "WidgetBase",
)
