"""
Material UI widgets, plus the classic widgets that have no Material equivalent.
"""
from panel_material_ui.widgets import (
    AutocompleteInput, Avatar, Breadcrumbs, Button, ButtonIcon, Checkbox,
    CheckBoxGroup, CheckButtonGroup, Chip, CircularProgress, ColorPicker,
    CrossSelector, DatePicker, DateRangePicker, DateRangeSlider, DateSlider,
    DatetimeInput, DatetimePicker, DatetimeRangePicker, DatetimeRangeSlider,
    DatetimeSlider, DictInput, DiscreteSlider, EditableFloatSlider,
    EditableIntRangeSlider, EditableIntSlider, EditableRangeSlider, Fab,
    FileDownload, FileInput, FloatInput, FloatSlider, IconButton, IntInput,
    IntRangeSlider, IntSlider, LinearProgress, ListInput, LiteralInput,
    LoadingSpinner, MenuBar, MenuButton, MenuList, MenuToggle, MultiChoice,
    MultiPill, MultiSelect, NestedBreadcrumbs, NestedSelect, NumberInput,
    Pagination, PasswordInput, Pill, Progress, RadioBoxGroup, RadioButtonGroup,
    RangeSlider, Rating, Select, SpeedDial, SplitButton, StepperMenu, Switch,
    TabMenu, TextAreaInput, TextInput, TimePicker, Toggle, ToggleIcon, Tree,
    TupleInput,
)

from ...widgets import (
    ArrayInput, BooleanStatus, CodeEditor, CompositeWidget, DatetimeRangeInput,
    Debugger, Dial, DiscretePlayer, FileDropper, FileSelector, Gauge, Grammar,
    GrammarList, JSONEditor, LinearGauge, Number, Player, SpeechToText,
    StaticText, Tabulator, Terminal, TextEditor, TextToSpeech, ToggleGroup,
    TooltipIcon, Tqdm, Trend, Utterance, VideoStream, Voice, Widget,
    WidgetBase,
)

__all__ = (
    "ArrayInput",
    "AutocompleteInput",
    "Avatar",
    "BooleanStatus",
    "Breadcrumbs",
    "Button",
    "ButtonIcon",
    "Checkbox",
    "CheckBoxGroup",
    "CheckButtonGroup",
    "Chip",
    "CircularProgress",
    "CodeEditor",
    "ColorPicker",
    "CompositeWidget",
    "CrossSelector",
    "DatePicker",
    "DateRangePicker",
    "DateRangeSlider",
    "DateSlider",
    "DatetimeInput",
    "DatetimePicker",
    "DatetimeRangeInput",
    "DatetimeRangePicker",
    "DatetimeRangeSlider",
    "DatetimeSlider",
    "Debugger",
    "Dial",
    "DictInput",
    "DiscretePlayer",
    "DiscreteSlider",
    "EditableFloatSlider",
    "EditableIntRangeSlider",
    "EditableIntSlider",
    "EditableRangeSlider",
    "Fab",
    "FileDownload",
    "FileDropper",
    "FileInput",
    "FileSelector",
    "FloatInput",
    "FloatSlider",
    "Gauge",
    "Grammar",
    "GrammarList",
    "IconButton",
    "IntInput",
    "IntRangeSlider",
    "IntSlider",
    "JSONEditor",
    "LinearGauge",
    "LinearProgress",
    "ListInput",
    "LiteralInput",
    "LoadingSpinner",
    "MenuBar",
    "MenuButton",
    "MenuList",
    "MenuToggle",
    "MultiChoice",
    "MultiPill",
    "MultiSelect",
    "NestedBreadcrumbs",
    "NestedSelect",
    "Number",
    "NumberInput",
    "Pagination",
    "PasswordInput",
    "Pill",
    "Player",
    "Progress",
    "RadioBoxGroup",
    "RadioButtonGroup",
    "RangeSlider",
    "Rating",
    "Select",
    "SpeechToText",
    "SpeedDial",
    "SplitButton",
    "StaticText",
    "StepperMenu",
    "Switch",
    "TabMenu",
    "Tabulator",
    "Terminal",
    "TextAreaInput",
    "TextEditor",
    "TextInput",
    "TextToSpeech",
    "TimePicker",
    "Toggle",
    "ToggleGroup",
    "ToggleIcon",
    "TooltipIcon",
    "Tqdm",
    "Tree",
    "Trend",
    "TupleInput",
    "Utterance",
    "VideoStream",
    "Voice",
    "Widget",
    "WidgetBase",
)
