#!/bin/bash
export BOKEH_ALLOW_WS_ORIGIN=hub.gke2.mybinder.org
export DISPLAY=:99.0
export PYVISTA_OFF_SCREEN=true
export PYVISTA_USE_IPYVTK=true
export PYVISTA_PLOT_THEME=document
which Xvfb
Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
sleep 3
exec "$@"