name: docs

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
  workflow_dispatch:
    inputs:
      target:
        description: "Site to build and deploy"
        type: choice
        options:
          - dev
          - main
          - dryrun
        required: true
        default: dryrun
  schedule:
    - cron: "0 19 * * SUN"

defaults:
  run:
    shell: bash -e {0}

env:
  DISPLAY: ":99.0"

jobs:
  pixi_lock:
    name: Pixi lock
    runs-on: ubuntu-latest
    steps:
      - uses: holoviz-dev/holoviz_tasks/pixi_lock@v0

  docs_build:
    name: Build Documentation
    needs: [pixi_lock]
    runs-on: "macos-latest"
    timeout-minutes: 180
    steps:
      - uses: holoviz-dev/holoviz_tasks/pixi_install@v0
        with:
          environments: docs
          opengl: true
      - name: Build documentation
        run: pixi run -e docs docs-build
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: docs
          if-no-files-found: error
          path: builtdocs

  docs_publish:
    name: Publish Documentation
    runs-on: "ubuntu-latest"
    needs: [docs_build]
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: docs
          path: builtdocs/
      - name: Deploy dev
        uses: peaceiris/actions-gh-pages@v4
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'dev') ||
          (github.event_name == 'push' && (contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc')))
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: holoviz-dev/panel
          publish_dir: ./builtdocs
          force_orphan: true
      - name: Deploy main
        uses: peaceiris/actions-gh-pages@v4
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'main') ||
          (github.event_name == 'push' && !(contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc')))
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builtdocs
          cname: panel.holoviz.org
          force_orphan: true
