name: downstream_tests

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: [packages]
    types: [completed]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  downstream_tests:
    name: Run downstream tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        downstream_repo: [holoviews, lumen]
      fail-fast: false
    steps:
      - uses: holoviz-dev/holoviz_tasks/downstream-tests@ffddda04b2894fea39b407f64d3622d2f19e5a9f # v1
        with:
          downstream_repo: ${{ matrix.downstream_repo }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
